# Generated by Django 6.0.4 on 2026-05-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва гри')),
                ('description', models.TextField(verbose_name='Опис гри')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Платформа (PC, PS5, etc.)')),
                ('games', models.ManyToManyField(to='lab3.game', verbose_name='Ігри на цій платформі')),
            ],
        ),
    ]
