# Generated by Django 6.0.4 on 2026-05-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0004_alter_game_genre_alter_game_image_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
